version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongo

  translator:
    image: dikshantniraula/huggingface-translator:latest
    ports:
      - 5000:5000
    depends_on:
      - mongo
