services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./logs:/app/logs
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/ultimate_translator_dev
      - ENCRYPTION_KEY=d7a3c3f8e5b6a8d9c0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2c3
    depends_on:
      - mongo
    networks:
      - translator-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - translator-network

volumes:
  mongo_data:
  node_modules:

networks:
  translator-network:
    driver: bridge 